/*
 * This file is generated by jOOQ.
 */
package org.coinpet.petcoin.crypto.repository.jooq.model.public_;


import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.CryptoExchange;
import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.Cryptocurrencies;
import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.Exchanges;
import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.FlywaySchemaHistory;
import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.MarketData;
import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.NotificationLogs;
import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.Subscriptions;
import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.crypto_exchange</code>.
     */
    public static final CryptoExchange CRYPTO_EXCHANGE = CryptoExchange.CRYPTO_EXCHANGE;

    /**
     * The table <code>public.cryptocurrencies</code>.
     */
    public static final Cryptocurrencies CRYPTOCURRENCIES = Cryptocurrencies.CRYPTOCURRENCIES;

    /**
     * The table <code>public.exchanges</code>.
     */
    public static final Exchanges EXCHANGES = Exchanges.EXCHANGES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.market_data</code>.
     */
    public static final MarketData MARKET_DATA = MarketData.MARKET_DATA;

    /**
     * The table <code>public.notification_logs</code>.
     */
    public static final NotificationLogs NOTIFICATION_LOGS = NotificationLogs.NOTIFICATION_LOGS;

    /**
     * The table <code>public.subscriptions</code>.
     */
    public static final Subscriptions SUBSCRIPTIONS = Subscriptions.SUBSCRIPTIONS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
