/*
 * This file is generated by jOOQ.
 */
package org.coinpet.petcoin.repository.jooq.model.public_;


import java.util.Arrays;
import java.util.List;

import org.coinpet.petcoin.repository.jooq.model.DefaultCatalog;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.CryptoExchange;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.Cryptocurrencies;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.Exchanges;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.MarketData;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.NotificationLogs;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.Subscriptions;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.Users;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.crypto_exchange</code>.
     */
    public final CryptoExchange CRYPTO_EXCHANGE = CryptoExchange.CRYPTO_EXCHANGE;

    /**
     * The table <code>public.cryptocurrencies</code>.
     */
    public final Cryptocurrencies CRYPTOCURRENCIES = Cryptocurrencies.CRYPTOCURRENCIES;

    /**
     * The table <code>public.exchanges</code>.
     */
    public final Exchanges EXCHANGES = Exchanges.EXCHANGES;

    /**
     * The table <code>public.market_data</code>.
     */
    public final MarketData MARKET_DATA = MarketData.MARKET_DATA;

    /**
     * The table <code>public.notification_logs</code>.
     */
    public final NotificationLogs NOTIFICATION_LOGS = NotificationLogs.NOTIFICATION_LOGS;

    /**
     * The table <code>public.subscriptions</code>.
     */
    public final Subscriptions SUBSCRIPTIONS = Subscriptions.SUBSCRIPTIONS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CryptoExchange.CRYPTO_EXCHANGE,
            Cryptocurrencies.CRYPTOCURRENCIES,
            Exchanges.EXCHANGES,
            MarketData.MARKET_DATA,
            NotificationLogs.NOTIFICATION_LOGS,
            Subscriptions.SUBSCRIPTIONS,
            Users.USERS
        );
    }
}
