/*
 * This file is generated by jOOQ.
 */
package org.coinpet.petcoin.repository.jooq.model.public_.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.coinpet.petcoin.repository.jooq.model.public_.Keys;
import org.coinpet.petcoin.repository.jooq.model.public_.Public;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.Cryptocurrencies.CryptocurrenciesPath;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.Users.UsersPath;
import org.coinpet.petcoin.repository.jooq.model.public_.tables.records.SubscriptionsRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Subscriptions extends TableImpl<SubscriptionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.subscriptions</code>
     */
    public static final Subscriptions SUBSCRIPTIONS = new Subscriptions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubscriptionsRecord> getRecordType() {
        return SubscriptionsRecord.class;
    }

    /**
     * The column <code>public.subscriptions.id</code>.
     */
    public final TableField<SubscriptionsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.subscriptions.user_id</code>.
     */
    public final TableField<SubscriptionsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.subscriptions.crypto_id</code>.
     */
    public final TableField<SubscriptionsRecord, Integer> CRYPTO_ID = createField(DSL.name("crypto_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.subscriptions.threshold</code>.
     */
    public final TableField<SubscriptionsRecord, BigDecimal> THRESHOLD = createField(DSL.name("threshold"), SQLDataType.NUMERIC(20, 8).nullable(false), this, "");

    /**
     * The column <code>public.subscriptions.notification_type</code>.
     */
    public final TableField<SubscriptionsRecord, String> NOTIFICATION_TYPE = createField(DSL.name("notification_type"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.subscriptions.created_at</code>.
     */
    public final TableField<SubscriptionsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Subscriptions(Name alias, Table<SubscriptionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Subscriptions(Name alias, Table<SubscriptionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.subscriptions</code> table reference
     */
    public Subscriptions(String alias) {
        this(DSL.name(alias), SUBSCRIPTIONS);
    }

    /**
     * Create an aliased <code>public.subscriptions</code> table reference
     */
    public Subscriptions(Name alias) {
        this(alias, SUBSCRIPTIONS);
    }

    /**
     * Create a <code>public.subscriptions</code> table reference
     */
    public Subscriptions() {
        this(DSL.name("subscriptions"), null);
    }

    public <O extends Record> Subscriptions(Table<O> path, ForeignKey<O, SubscriptionsRecord> childPath, InverseForeignKey<O, SubscriptionsRecord> parentPath) {
        super(path, childPath, parentPath, SUBSCRIPTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SubscriptionsPath extends Subscriptions implements Path<SubscriptionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SubscriptionsPath(Table<O> path, ForeignKey<O, SubscriptionsRecord> childPath, InverseForeignKey<O, SubscriptionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SubscriptionsPath(Name alias, Table<SubscriptionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SubscriptionsPath as(String alias) {
            return new SubscriptionsPath(DSL.name(alias), this);
        }

        @Override
        public SubscriptionsPath as(Name alias) {
            return new SubscriptionsPath(alias, this);
        }

        @Override
        public SubscriptionsPath as(Table<?> alias) {
            return new SubscriptionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SubscriptionsRecord, Integer> getIdentity() {
        return (Identity<SubscriptionsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<SubscriptionsRecord> getPrimaryKey() {
        return Keys.SUBSCRIPTIONS_PKEY;
    }

    @Override
    public List<UniqueKey<SubscriptionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQ_USER_CRYPTO);
    }

    @Override
    public List<ForeignKey<SubscriptionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SUBSCRIPTIONS__SUBSCRIPTIONS_CRYPTO_ID_FKEY, Keys.SUBSCRIPTIONS__SUBSCRIPTIONS_USER_ID_FKEY);
    }

    private transient CryptocurrenciesPath _cryptocurrencies;

    /**
     * Get the implicit join path to the <code>public.cryptocurrencies</code>
     * table.
     */
    public CryptocurrenciesPath cryptocurrencies() {
        if (_cryptocurrencies == null)
            _cryptocurrencies = new CryptocurrenciesPath(this, Keys.SUBSCRIPTIONS__SUBSCRIPTIONS_CRYPTO_ID_FKEY, null);

        return _cryptocurrencies;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.SUBSCRIPTIONS__SUBSCRIPTIONS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public Subscriptions as(String alias) {
        return new Subscriptions(DSL.name(alias), this);
    }

    @Override
    public Subscriptions as(Name alias) {
        return new Subscriptions(alias, this);
    }

    @Override
    public Subscriptions as(Table<?> alias) {
        return new Subscriptions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Subscriptions rename(String name) {
        return new Subscriptions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subscriptions rename(Name name) {
        return new Subscriptions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subscriptions rename(Table<?> name) {
        return new Subscriptions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Subscriptions where(Condition condition) {
        return new Subscriptions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Subscriptions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Subscriptions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Subscriptions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Subscriptions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Subscriptions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Subscriptions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Subscriptions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Subscriptions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Subscriptions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
