/*
 * This file is generated by jOOQ.
 */
package org.coinpet.petcoin.repository.jooq.model.public_.tables.records;


import java.time.LocalDateTime;

import org.coinpet.petcoin.repository.jooq.model.public_.tables.Exchanges;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ExchangesRecord extends UpdatableRecordImpl<ExchangesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.exchanges.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.exchanges.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.exchanges.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.exchanges.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.exchanges.website</code>.
     */
    public void setWebsite(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.exchanges.website</code>.
     */
    public String getWebsite() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.exchanges.country</code>.
     */
    public void setCountry(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.exchanges.country</code>.
     */
    public String getCountry() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.exchanges.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.exchanges.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExchangesRecord
     */
    public ExchangesRecord() {
        super(Exchanges.EXCHANGES);
    }

    /**
     * Create a detached, initialised ExchangesRecord
     */
    public ExchangesRecord(Integer id, String name, String website, String country, LocalDateTime createdAt) {
        super(Exchanges.EXCHANGES);

        setId(id);
        setName(name);
        setWebsite(website);
        setCountry(country);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
