/*
 * This file is generated by jOOQ.
 */
package org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.records;


import java.time.LocalDateTime;

import org.coinpet.petcoin.crypto.repository.jooq.model.public_.tables.NotificationLogs;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NotificationLogsRecord extends UpdatableRecordImpl<NotificationLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.notification_logs.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.notification_logs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.notification_logs.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.notification_logs.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.notification_logs.crypto_id</code>.
     */
    public void setCryptoId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.notification_logs.crypto_id</code>.
     */
    public Integer getCryptoId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.notification_logs.notification_time</code>.
     */
    public void setNotificationTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.notification_logs.notification_time</code>.
     */
    public LocalDateTime getNotificationTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.notification_logs.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.notification_logs.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.notification_logs.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.notification_logs.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationLogsRecord
     */
    public NotificationLogsRecord() {
        super(NotificationLogs.NOTIFICATION_LOGS);
    }

    /**
     * Create a detached, initialised NotificationLogsRecord
     */
    public NotificationLogsRecord(Integer id, Integer userId, Integer cryptoId, LocalDateTime notificationTime, String message, String status) {
        super(NotificationLogs.NOTIFICATION_LOGS);

        setId(id);
        setUserId(userId);
        setCryptoId(cryptoId);
        setNotificationTime(notificationTime);
        setMessage(message);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
